#!/usr/bin/env bash

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

set -a
. $ABSOLUTE_PATH/env
set +a

PS1="(do) $PS1"

?() {
  bash -c ". '$ABSOLUTE_PATH/bashrc'; typeset -F | cut -d' ' -f3 | grep -v ^__"
}

__curl-do() {
  curl -X ${1:-GET} "https://api.digitalocean.com/v2/$2" -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" "${@:3}"
}

__ssh-key-fingerprint() {
  ssh-keygen -E md5 -lf "$PUBLIC_SSH_KEY_FILE" | cut -d' ' -f2 | cut -c5-
}

list-ssh-keys() {
  __curl-do GET account/keys "$@"
}

list-ssh-key() {
  __curl-do GET "account/keys/$(__ssh-key-fingerprint)" "$@"
}

create-ssh-key() {
  __curl-do POST account/keys -d "$(<"$PUBLIC_SSH_KEY_FILE" jq -Rs '{name: "Personal", public_key: .}')" "$@"
}

delete-ssh-key() {
  local ssh_key_id="$1"
  __curl-do DELETE "account/keys/$ssh_key_id" -d '' "$@"
}

list-droplets() {
  __curl-do GET droplets "$@"
}

create-droplet() {
  local data="$(<"$ABSOLUTE_PATH/droplet.json" jq --arg name "$1" --arg ssh_key "$(__ssh-key-fingerprint)" '.name |= $name | .ssh_keys |= . + [$ssh_key]')"
  __curl-do POST droplets -d "$data" "${@:2}"
}

__droplet-id() {
  list-droplets | jq -r --arg name "$1" '.droplets | map(select(.name == $name)) | first | .id'
}

__droplet-ip() {
  list-droplets | jq -r --arg name "$1" '.droplets | map(select(.name == $name)) | first | .networks.v4 | first | .ip_address'
}

delete-droplet() {
  local droplet_id="$(__droplet-id "$1")"
  __curl-do DELETE "droplets/$droplet_id" -d '' "${@:2}"
}

ssh-droplet() {
  ssh "root@$(__droplet-ip "$1")"
}

list-volumes() {
  __curl-do GET volumes "$@"
}

create-volume() {
  local data="$(<"$ABSOLUTE_PATH/volume.json" jq --arg name "$1" '.name |= $name')"
  __curl-do POST volumes -d "$data" "${@:2}"
}

__volume-id() {
  list-volumes | jq -r --arg name "$1" '.volumes | map(select(.name == $name)) | first | .id'
}

delete-volume() {
  read -p 'enter the volume id: ' given_volume_id
  local volume_id="$(__volume-id "$1")"
  test "$given_volume_id" = "$volume_id" || exit 1
  __curl-do DELETE "volumes/$volume_id" -d '' "${@:2}"
}

attach-volume() {
  local droplet_id="$(__droplet-id "$2")"
  local data="$(jq -n --arg volume_name "$1" --argjson droplet_id "$droplet_id" '{type:"attach",volume_name:$volume_name,"droplet_id":$droplet_id}')"
  __curl-do POST "volumes/actions" -d "$data" "${@:3}"
}

detach-volume() {
  local droplet_id="$(__droplet-id "$2")"
  local data="$(jq -n --arg volume_name "$1" --argjson droplet_id "$droplet_id" '{type:"detach",volume_name:$volume_name,"droplet_id":$droplet_id}')"
  __curl-do POST "volumes/actions" -d "$data" "${@:3}"
}
