#!/usr/bin/env bash

ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

set -a
. $ABSOLUTE_PATH/env
set +a

PS1="(do) $PS1"

?() {
  bash -c ". '$ABSOLUTE_PATH/bashrc'; typeset -F | cut -d' ' -f3 | grep -v ^__"
}

__curl-do() {
  curl -X ${1:-GET} "https://api.digitalocean.com/v2/$2" -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" "${@:3}"
}

__ssh-key-fingerprint() {
  ssh-keygen -E md5 -lf "$PUBLIC_SSH_KEY_FILE" | cut -d' ' -f2 | cut -c5-
}

list-ssh-keys() {
  __curl-do GET account/keys
}

list-ssh-key() {
  __curl-do GET "account/keys/$(__ssh-key-fingerprint)"
}

create-ssh-key() {
  __curl-do POST account/keys -d "$(<"$PUBLIC_SSH_KEY_FILE" jq -Rs '{name: "Personal", public_key: .}')"
}

delete-ssh-key() {
  local ssh_key_id="$1"
  __curl-do DELETE "account/keys/$ssh_key_id" -d ''
}

list-volumes() {
  __curl-do GET volumes
}

__volume-json() {
  jq -n -f "$ABSOLUTE_PATH/volume.jq"
}

create-volume() {
  __curl-do POST volumes -d "$(__volume-json)"
}

__volume-name() {
  __volume-json | jq -r .name
}

__volume-id() {
  list-volumes | jq -r --arg name "$(__volume-name)" '.volumes | map(select(.name == $name)) | first | .id'
}

delete-volume() {
  __curl-do DELETE "volumes/$(__volume-id)" -d ''
}

list-droplets() {
  __curl-do GET droplets
}

__droplet-json() {
  local user_data="$(./write-mime-multipart init.sh:x-shellscript init.conf:cloud-config)"
  jq -n --arg ssh_key "$(__ssh-key-fingerprint)" --arg volume "$(__volume-id)" --arg user_data "$user_data" -f "$ABSOLUTE_PATH/droplet.jq"
}

create-droplet() {
  __curl-do POST droplets -d "$(__droplet-json)"
}

__droplet-name() {
  __droplet-json | jq -r .name
}

__droplet-id() {
  list-droplets | jq -r --arg name "$(__droplet-name)" '.droplets | map(select(.name == $name)) | first | .id'
}

list-droplet() {
  __curl-do GET "droplets/$(__droplet-id)"
}

__droplet-ip() {
  list-droplet | jq -r '.droplet.networks.v4 | first | .ip_address'
}

delete-droplet() {
  __curl-do DELETE "droplets/$(__droplet-id)" -d ''
}

ssh-droplet() {
  ssh "root@$(__droplet-ip)"
}
