name: DigitalOcean functions
on: [workflow_dispatch]
defaults:
  run:
    working-directory: digitalocean/functions
jobs:
  Create-function:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: npm install
      - env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: ./do deploy