name: Deploy on Netlify
on: [push, workflow_dispatch]
defaults:
  run:
    working-directory: netlify
jobs:
  Deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls -al
      - run: npm install
      - env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: ./do deploy