name: Deploy on Netlify
on: [push]
defaults:
  run:
    working-directory: netlify
jobs:
  Deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: ./do deploy