name: Deploy on Netlify
on:
  push:
    paths:
      - netlify/
  workflow_dispatch:
    inputs:
      URL:
        description: URL
        required: true
        default: draft
        type: choice
        options:
        - draft
        - main site
defaults:
  run:
    working-directory: netlify
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls -al
      - run: npm install
      - run: ./do authorize-netlify
      - run: |
          case '${{inputs.URL}}' in
            '' | draft)
              ./do deploy;;
            'main site')
              ./do deploy --prod;;
            *) exit 1;;
          esac | tee deploy.json
  Test:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Test static page
        run: curl $(<deploy.json jq -r .deploy_url) | grep 'Hello, World!'
      - name: Test function
        run: curl $(<deploy.json jq -r .deploy_url)/.netlify/functions/first | jq -e '.message == "Hello World"'
      - name: Test edge function
        run: curl $(<deploy.json jq -r .deploy_url)/hello | grep 'Hello, World!'
        continue-on-error: true